# Generated by Django 3.1 on 2020-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.FileField(blank=True, null=True, upload_to='beats')),
                ('image', models.ImageField(blank=True, null=True, upload_to='beat_image')),
                ('title', models.CharField(max_length=100)),
                ('produced_By', models.CharField(max_length=100)),
            ],
        ),
    ]
