# Generated by Django 3.1 on 2020-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Instrument_images')),
                ('sound', models.FileField(upload_to='Instrument_sounds')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
